version: '3.8'
services:
  mongo:
    image: mongo
    restart: always
    
  mongo-express:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://localhost:27017/
  
  server:
    container_name: atlas_icons_api
    restart: unless-stopped
    image: atlas_icons-api-prod:1.0.0
    build: 
      context: server
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    
    depends_on:
      - mongo

  client:
    container_name: atlas_icons_client
    restart: unless-stopped
    image: atlas_icons-client-prod:1.0.0
    build: 
      context: client
      dockerfile: Dockerfile
    ports:
      - 8080:8081
    depends_on:
      - server